README.md
lib/index.js
package.json
test/index.js

Per #32 I've refactored the module to use the aws-sdk instead of Knox.
I haven't added or removed any functionality -- just replaced Knox and dependent modules with aws-sdk and one other dependency.
I think this is worthwhile because it seems aws-sdk will have better long term support. I'd also like to add functionality that handles the `putBucketWebsite` for a more complete package, and I found that nearly impossible to do with Knox.

refactored to use aws-sdk instead of knox

---

lib/index.js

The recent switch to aws-sdk broke non-standard regions. `config.region` didn't get passed to S3 anymore.
This fixes it.

config: fix region setting

---

lib/index.js

This check that is being removed prevents gulp-awspublish from working
correctly on EC2 instances configured with an IAM Instance Profile.
The AWS SDK will bail out if credentials are incorrectly configured.

Don't attempt to validate credentials [Fixes #45]

---

lib/index.js

The README mentions "a profile property for choosing a specific set of shared AWS creds".
Here is an example where a profile is supplied:
```
awsPublisher = function awsPublisher() {
var aws = {
profile: 'my-profile',
bucket: 'my-s3-bucket'
};
return awspublish.create(aws);
};
```
Currently this does not work. The `profile` value is ignored in favour of the default profile in `~/.aws/credentials`.
This pull request fixes this and ensures the profile is respected by using `AWS.SharedIniFileCredentials` instead of `AWS.config.credentials` if a profile is supplied. 
This appears to be the recommended method in the AWS SDK docs - http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Using_Profiles_with_the_SDK

Respect AWS credentials profile when supplied in options

---

lib/index.js
test/index.js

Hello! Thanks for creating a very helpful package.
I'm having some issues with syncing gzipped encoded assets. Currently they're being synced with `application/octet-stream` rather than their original content type which makes my app unable to serve up the gzipped assets.
This fixes the issue for me - does this seem sane?

Preserve content type header on gzip

---

README.md
lib/index.js
test/index.js

Currently most configuration [options that S3 can take in](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property) are stripped out, which is very unfortunate. 
This patch changes to take in and pass through the options directly without any mangling or manipulation.
This should be released as version 2.0 to avoid breaking people's existing code.

Fixes how publisher takes in configuration to allow all S3 options to be passed in

---

lib/index.js

Nice gulp plugin, thanks for writing it!
headObject returns a 403 error (possibly because the user has ListBucket permission, while the s3 bucket itself does not.)  Confirmed it's one of the possible errors we should expect according to the docs.
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html

Expect 403 response for headObject

---

lib/index.js

When trying to supply my own `Content-Type` header, I found it to not be sent to S3 correctly.
@skyzyx seems to experience this issue [as well](https://github.com/jussi-kalliokoski/gulp-awspublish-router/issues/7). 
This is exacerbated since Content-Type detection seemed unreliable for gzipped assets — it often set `application/octet-stream` instead of `text/…`.
This fix simply checks whether these two header values were already supplied before setting them.

Don't overwrite Content-Type and Content-Length header values

---

README.md
package.json

Require node `0.12` or later to avoid #86.
Tested successfully in node versions `0.12.0`, `0.12.7`, and `4.1.0`.

Bump Node engine requirement to 12.x

---

README.md

This is to help avoid an "error" when aws issues a 301 redirect when publishing to a bucket, apparently only there is a '.' in the bucket name. By including the region, and all buckets are defined with a region, the error is always avoided. The command line client puts this in it's profile file under .aws.

Added region to the docs as it should really always be present.

---

README.md

This section was incorrect in a few places. I updated it with example configuration objects for two of the most popular credential methods.

Improve credentials section of README.md

---

README.md
lib/index.js

Add ability to define the location of the cache and the visibility of the hash file itself.
The background is that we use several plugins and some custom code for caching in production. Ideally we wanted them to store all the digests in one dedicated folder and not in the root. Also, the fact that the file was hidden by default made it hard to view it in the AWS-S3 console. That option was purely for more convenience.

Cache file options

---

README.md
lib/index.js
test/index.js

- Adds test that check both if the custom named cache files are created, or if the cache options are missing, than the default cache file is created.
- I also run into some problems while trying to run the tests, so I refactored the testing part of the README a little bit.
- Finally in the Publisher class' constructor, the parameter names (config and options) were pretty generic, so I renamed them (this is just renaming, nothing breaking here).
The issue I'm solving with this PR:
https://github.com/pgherveou/gulp-awspublish/issues/112

Adds tests for cacheOptions

---

README.md
lib/index.js
test/index.js

This pull request is an attempt to resolve #107
Sync method now receives an options object as only param.
The options are:
- prefix: prefix to sync a specific directory
- whitelist: array of strings or regular expressions to match against filenames that should not be deleted from the bucket

Refactor sync method to allow exclusions in file deletions

---

README.md
lib/index.js
test/index.js

In cases where bucket access is controlled by bucket policy, and where
the credentials used for upload do not allow PutObjectAcl (which is
actually a very powerful call!), it's best not to specify x-amz-acl at
all.  This provides an option to `publisher.publish` to skip adding
this default header.

Add `publish(.., {noAcl: true})` option

---

README.md

The docs of sync method are wrong, the method actually receives two params, and not an options param.

Fix docs of sync method

---

lib/converter.js
lib/index.js
package.json

This PR removes the `xml-json` dependency and replaces it with `lib/converter.js`.  This is identical to [xml-json/index.js](https://github.com/maxogden/xml-json/blob/master/index.js) without the `extend` dep for passing extra options.
Why?
`xml-json` is tiny, untested, 2yrs unmaintained, and its outdated dependency `xml-objects` is failing on CircleCI (see https://github.com/maxogden/xml-json/pull/2).  The updated `xml-objects` [uses `through2` streams](https://github.com/timhudson/xml-objects/commit/e75e39723fffa3cd3f0c54f82549427f44e9f14f) and has no issues.  I figure it is best to just add to the lib here instead of trying to update the abandoned `xml-json` dep.
I've confirmed `publisher.sync()` is working on this fork, both locally and on CI.

Drop unmaintained xml-json for lib/converter.js

---

examples/events.js
examples/rename.js
lib/index.js
lib/log-reporter.js
package.json
test/index.js

Drop dependency on deprecated `gulp-util`

---

lib/index.js
package.json

The current `mime` dependency has this vulnerability https://nodesecurity.io/advisories/535. 
I thinking about replacing it with https://www.npmjs.com/package/mime-types which is almost a drop-in replacement.
Thought about updating to `mime@2` but seems like it won't support charsets anymore 🤔

Use mime-types to solve insecure dependency

---

README.md

Resolving https://github.com/pgherveou/gulp-awspublish/issues/144
I saw the PR https://github.com/pgherveou/gulp-awspublish/pull/135 but few minor things keep me from merging it right directly (ping @gfrivolt 🙏):
- The bracket style is different 😅 
- The JS example (without the `credentials` property) is actually valid based on AWS.S3 documentation https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor-property. I didn't go deep in the code/doc but seems like setting `signatureVersion` requires `credentials` property.

Fix JSON example in README.md

---

lib/index.js
test/index.js

It didn't take too long until I broke the plugin https://github.com/pgherveou/gulp-awspublish/issues/150 😓 
I replaced a dependency (https://github.com/pgherveou/gulp-awspublish/pull/147) without reading the difference carefully 🙈 
In https://www.npmjs.com/package/mime-types:
>No fallbacks. Instead of naively returning the first available type, mime-types simply returns false, so do var type = mime.lookup('unrecognized') || 'application/octet-stream'.

Use fallback when MIME lookup fails

---

test/index.js

Fixing the following warning:
```
(node:7119) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

Replace "new Buffer()" with "Buffer.from()"

---

lib/index.js
test/index.js

This pull request adds an option to `gzip` to only produce gzipped files when the resulting size is smaller than the original file. Some files don't benefit from gzipping and see an increase in size, this option is allows the file to be left alone in this case and uploaded without gzip.
(*Sorry if this pull request is a little unclear, it's late here*).

Add option to gzip to skip larger gzip files

---

lib/s3-paging-stream.js

A couple of days ago I updated all of my dev dependencies for a project that uses library. At that time, my sync stopped working and I've been banging my head against the why of it. It turns out, that likely either: 
1) Due to some combination of update of dependencies, an assumption in the s3pagingStream is no longer true: that the stream will receive another call to `read` after the `page_handler` has completed, or
2) Some other change in my environment caused multiple pages to run in `sync` and it never had before. That's possible because a change in filename hash as part of my dependencies bump means that when I run this today a whole bunch of static assets are getting a new filename, meaning that the bucket is much more full than usual and therefore to finish the sync, multiple pages …

[FIX] Stream completion in sync

---

lib/log-reporter.js
package-lock.json
package.json

Using the string method `padEnd()` instead (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd)

Replace 'pad-component' with padEnd()

---

.gitignore
package-lock.json
package.json

I am removing everything related to test coverage. I don't find where Coveralls is used, I don't see any coverage report after running the tests and those reporters are not maintained for years.
If we need test coverage, it will be easy to add with nyc and just run `nyc mocha`. But nyc pulls oudated dependencies too 💦 Anyway, this repo should be fine without test coverage.

Remove outdated test coverage

---

package.json
test/index.js

`clone` is used once during the tests for a very simple object. Removing it since it can be easily replaced with vanilla JS in this case.

Remove clone from dependencies

---

package-lock.json
package.json

- https://github.com/gulpjs/plugin-error/releases/tag/v2.0.0
- https://github.com/gulpjs/vinyl/releases/tag/v3.0.0
- https://github.com/mochajs/mocha/releases/tag/v10.0.0 (💥 dropping Node 12 support)
- Lockfile generated with npm v9
Tests are passing on my fork https://github.com/pioug/gulp-awspublish/actions/runs/3604137147 (no permissions to run them in this repo).

Update dependencies (use lockfile v3)

---

README.md
lib/index.js
test/index.js

I've encountered this issue recently while working with a private bucket. I'd like to improve the "default" behavior
1. We can reduce the API surface by removing the `noAcl` option because it's already possible to set headers via the first argument.   
2. From what I understand, when not explicitly specified, objects inherit the settings from the bucket, which seems more suitable for common cases than letting the plugin set them to 'public' by default.
I will release a major version since it's a breaking change.

Do not pass any ACL header by default
